### ISSUE TITLE
TypeError: __html.replace is not a function

### ISSUE THREAD

**Issue by sambrannon** [jonkemp/gulp-inline-css#50] opened 2018-03-06 04:24 UTC
I have a basic example (as detailed below) that throws this error whenever I run

```bash
$ gulp
```

Using `gulp-inline-css` version `3.1.2`

```bash
Unhandled rejection TypeError: __html.replace is not a function
    at /Users/sam/Projects/Personal/gulp-premailer-example/node_modules/list-stylesheets/index.js:27:33
    at Array.forEach (native)
    at encodeCodeBlocks (/Users/sam/Projects/Personal/gulp-premailer-example/node_modules/list-stylesheets/index.js:24:33)
    at encodeEntities (/Users/sam/Projects/Personal/gulp-premailer-example/node_modules/list-stylesheets/index.js:45:20)
    at module.exports (/Users/sam/Projects/Personal/gulp-premailer-example/node_modules/list-stylesheets/index.js:52:22)
    at module.exports (/Users/sam/Projects/Personal/gulp-premailer-example/node_modules/extract-css/index.js:11:16)
    at /Users/sam/Projects/Personal/gulp-premailer-example/node_modules/inline-css/lib/inlineContent.js:15:9
    at Promise._execute (/Users/sam/Projects/Personal/gulp-premailer-example/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/sam/Projects/Personal/gulp-premailer-example/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/sam/Projects/Personal/gulp-premailer-example/node_modules/bluebird/js/release/promise.js:79:10)
    at inlineContent (/Users/sam/Projects/Personal/gulp-premailer-example/node_modules/inline-css/lib/inlineContent.js:8:12)
    at /Users/sam/Projects/Personal/gulp-premailer-example/node_modules/inline-css/index.js:31:9
    at Promise._execute (/Users/sam/Projects/Personal/gulp-premailer-example/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/sam/Projects/Personal/gulp-premailer-example/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/sam/Projects/Personal/gulp-premailer-example/node_modules/bluebird/js/release/promise.js:79:10)
    at module.exports (/Users/sam/Projects/Personal/gulp-premailer-example/node_modules/inline-css/index.js:8:12)
```

gulpfile.js:
```js
var gulp = require('gulp'),
    inlineCss = require('gulp-inline-css');

gulp.task('default', function() {
  return gulp.src('./src/*.html')
    .pipe(inlineCss())
    .pipe(gulp.dest('build/'));
});
```

package.json
```json
{
  ...
  "dependencies": {
    "gulp": "^3.9.1",
    "gulp-inline-css": "^3.1.2"
  }
}
```

current setup
```
.
├── gulpfile.js
├── node_modules
│   └── ...
├── package.json
├── src
│   ├── css
│   │   └── style.css
│   └── template.html
└── yarn.lock
```

Tried downgrading to different version with no luck. Any help/insight would be appreciated.

**Comment by pzontrop** [comment] 2018-03-06 10:10
Funny I land here with the same error exactly one the same day this has been posted. Also trying lots of things like downgrading this and other packages... no success so far.

**Comment by evanre** [comment] 2018-03-06 10:25
+1. Is this can be related to the [new inline-css](https://github.com/jonkemp/inline-css/releases/tag/v2.3.0) version?

**Comment by svossen** [comment] 2018-03-06 11:28
Got it working when using `list-stylesheets` `1.1.1` instead of [1.2.0](https://github.com/jonkemp/list-stylesheets/tree/v1.2.0). Also with the new `inline-css` version

**Comment by jonkemp** [comment] 2018-03-06 14:16
Yes @evanre and @svossen are both correct. The inline-css update broke the gulp plugin. I forgot to test the gulp plugin before the release so my apologies for that. I have a potential fix which I hope to get out tonight. 

In the meantime, you would need to fix the package versions or just use inline-css directly, as the problem is not in inline-css itself but in the interaction between gulp-inline-css and inline-css.

**Comment by Gazler** [comment] 2018-03-06 16:13
I have a fix for this at https://github.com/jonkemp/gulp-inline-css/pull/51

**Comment by jonkemp** [comment] 2018-03-06 16:27
Thanks @Gazler but the pull request is not needed. As I said above, I already have the fix.

**Comment by gpspake** [comment] 2018-03-06 17:56
We're at a hackathon and we really needed this. Right now the master branch is broken but we were able to get it working with @Gazler's fork. Thanks @Gazler. Perfect timing :)

**Comment by jonkemp** [comment] 2018-03-06 18:33
That's fortunate then.

For those that are having trouble with the plugin, I recommend using a lock file going forward which locks all your packages to a certain version and doesn't update them unless you tell it to.

**Comment by jonkemp** [comment] 2018-03-06 23:28
Fix version is available. 195e7b9ae9a4d7b68277c769d5ce0f70a86a5a61

**Closed by jonkemp** 2018-03-06 23:28 UTC
