### ISSUE TITLE
Something's broken in the inline-css engine

### ISSUE THREAD

**Issue by mrcasual** [jonkemp/gulp-inline-css#20] opened 2015-03-05 00:57 UTC
I can't pinpoint exactly what's broken (haven't spent time reviewing the code) but I have run ```gulp-inline-css``` on some complex HTML+CSS file combinations and the end-result never seems right.

For instance, use the following for testing: [HTML](https://gist.github.com/mrcasual/8056d5bfdf4ccf057342) and [CSS](https://gist.github.com/mrcasual/47c0a11046855f24d29a).

Open the generated HTML file and take note of the ```table.container``` width (640px). Now, compare that with [results](https://gist.github.com/mrcasual/5f14f68ace89bb5dce26) from Zurb's inliner (it uses [Premailer](https://github.com/premailer/premailer)) where the width is 600px and the target looks exactly the same as the source.

**Comment by jonkemp** [comment] 2015-04-09 19:05
Ok, I've looked into this and here is the issue. In your linked stylesheet, you have this rule.
```css
td.wrapper {
  padding: 10px 20px 0px 0px;
  position: relative;
}
```

In your HTML, you have this rule in a style block.
```css
table.columns td, table.column td, td.wrapper { padding: 0; }
```

This is the same selector with different values for padding. It appears that premailer is applying the one from the style tag while inline-css is applying the one from the stylesheet.

So, I don't think anything is broken here. The inline-css module doesn't have a way to tell which one is correct since they are the same. It may be correct that it should apply the one in the style tag, but what if you have a stylesheet after that? I think the solution is to only use one rule to apply this style or override it with an inline style. I think the inline style would take precedence in this case and fix your issue.

**Comment by mrcasual** [comment] 2015-04-09 19:18
Thanks. 

One thing to keep in mind: external style sheets can only be included inside ```<head>``` elements using ```<link>``` tags (well, at least that's the valid HTML way) whereas ```<style>``` tags can be included inside ```<body```> as well, which allows them to override all previous styles. Inline styles, obviously, should override both. I personally think that Premailer's approach makes sense in this case.

**Comment by jonkemp** [comment] 2015-04-09 19:26
Yeah, I'm curious as to how premailer is doing that.

**Comment by andrewmclagan** [comment] 2015-08-27 07:29
... any movement on this issue? Im wrestling with it also.

**Comment by jonkemp** [comment] 2015-08-27 13:50
I'm going to close this since the title is misleading here and the question was resolved months ago. There is no bug here. The issue is with the way the CSS was written. Only two people having this issue doesn't seem like a pressing need. If you want to change the way this works in this plugin then make a feature request, write tests, submit a pull request, whatever. Thanks.

**Closed by jonkemp** 2015-08-27 13:50 UTC
