### ISSUE TITLE
Disable rewriting of language or template specific parts.

### ISSUE THREAD

**Issue by Jaspur** [jonkemp/gulp-inline-css#4] opened 2014-03-23 20:04 UTC
At the moment the following isn't working, when you make use of TemplateParsers:

```
// from
<p>Dear {{ $person->user->firstname }},</p>
// to
<p>Dear {{ $person-&gt;user-&gt;firstname }},</p>
```

And the following code is also incorrect parsed:

```
// from
<?php
$demo = Demo::whereEmail($email)->first();
?>
// to
first();
?&gt;
```

**Comment by kaiserkoenig** [comment] 2015-01-05 14:45
That's not what i want to hear ;O)
Any idea?

**Comment by jonkemp** [comment] 2015-01-05 15:16
Ok closing again. If you want something done about this, please address the issue in the [juice](https://github.com/LearnBoost/juice) repo. The issue is NOT here. Thanks.

**Comment by LekeFly** [comment] 2015-01-15 12:55
Has anyone found a gulp plugin or a workaround for this?

**Comment by kaiserkoenig** [comment] 2015-01-15 13:14
nope, but i opened an issue im juice repo.

**Comment by jonkemp** [comment] 2015-02-08 05:14
Anyone willing to try this now? This plugin uses inline-css which took juice and rewrote it to use cheerio.js instead of jsdom. I have tested it with mustache-style templates and it seems to work.

**Comment by kaiserkoenig** [comment] 2015-02-09 15:06
nearly! just some "" in SMARTY-tag become &qout;

[{include file="email/html/footer.tpl"}]
[{include file=& quot; email/html/footer.tpl & quot;}]

**Comment by jrit** [comment] 2015-02-18 02:11
In case you want to try, juice v1.0.0 seems to resolve these issues. I used some test cases from this issue just to be sure. I'd be interested to know if you still see problems.

**Comment by PeterSiegl** [comment] 2015-03-20 06:50
Any updates on this issue? 

I have the same problem using the Liquid templating language. Quotes and apostrophes inside tags are parsed to `&quot;` and `&apos;`.

**Comment by PawelGIX** [comment] 2015-04-08 13:59
I have this issue:
Example text: utf-8 "Wartość raty wyliczonej w kalkulatorze stanowi wartość orientacyjną dla Kredytu Obrotowego Ratalnego, przy uwzględnieniu parametrów takich jak: oprocentowanie 10%, maksymalna kwota kredytu 375 000 zł, maksymalny okres – 10 lat."
And result:
Warto&#x15B;&#x107; raty wyliczonej w kalkulatorze stanowi warto&#x15B;&#x107; orientacyjn&#x105; dla Kredytu Obrotowego Ratalnego, przy uwzgl&#x119;dnieniu parametr&#xF3;w takich jak: oprocentowanie 10%, maksymalna kwota kredytu 375 000 z&#x142;, maksymalny okres &#x2013; 10 lat.

**Comment by jonkemp** [comment] 2015-04-08 22:53
I updated the dependencies to not decode those entities. That was probably the cause. Make sure you have all the latest dependencies and see if it still occurs.

**Comment by PawelGIX** [comment] 2015-04-16 14:32
npm uninstall && npm install, fixed my issue

**Comment by yuchunc** [comment] 2017-04-04 08:38
Hi, seems like gulp-inline-css has switch over to inline-css. I am trying to render Elixir's template tags `<%=` `%>` in foundation email, and failing because of the angle brackets. How do I configure gulp-inline-css to take custom tags?

Thank You!

**Comment by jonkemp** [comment] 2018-03-07 02:21
The latest update should now have support for this.

https://github.com/jonkemp/gulp-inline-css#optionscodeblocks

**Closed by jonkemp** 2018-03-07 02:21 UTC
