### ISSUE TITLE
Do not trim spaces inside calc()

### ISSUE THREAD

**Issue by untone** [jonkemp/gulp-inline-css#37] opened 2016-06-13 18:41 UTC
Case:

foo { calc(100% - 100px)} inlines as <foo style="calc(100%-100px)">, without spaces around minus sign.

**Comment by nickdeamons** [comment] 2016-07-29 17:20
This is an issue for me as well.

**Comment by michellocana** [comment] 2016-08-02 16:11
I'm having the same issue, any workaround?

**Comment by michellocana** [comment] 2016-08-02 17:11
Ok, i got this working: https://gist.github.com/michellocana/7b58fc5e46d9bed28d903921b968c143
I used gulp-replace plugin to fix the trim inside calc() function. Not the better solution, but will do for now :)

**Comment by Elric-pp** [comment] 2016-09-26 09:49
It also remove spaces in linear-gradient
`linear-gradient(135deg, #00689b 0%, #00375a 90%, #00375a 90%, #003455 100%);`
to
`linear-gradient(135deg, #00689b0%, #00375a90%, #00375a90%, #003455100%);`

**Comment by dclaze** [comment] 2017-01-17 23:27
Bump

**Comment by jonkemp** [comment] 2017-01-18 15:34
The issue is in this module:

https://github.com/NV/CSSOM/

I've created an issue for this here.

https://github.com/NV/CSSOM/issues/86

**Comment by jonkemp** [comment] 2017-01-20 19:14
The issue in CCSOM was fixed so it should be available in their next release.

**Comment by jonkemp** [comment] 2017-01-26 03:06
I'm closing this as it's been resolved in the latest release of the cssom module. If you update your dependencies, it should work. If it's not working, make sure you have cssom 0.3.2.

**Closed by jonkemp** 2017-01-26 03:06 UTC
